<div class="row">

    <div class="span">
        <h2><?php echo sprintf($this->translate('About %s'), 'darkstar') ?></h2>
        <p><?php echo sprintf($this->translate('darkstar is under active development. If you are interested in following the development of darkstar, you can follow our %sdev blog%s and the source code on %sgithub%s'),'<a href="http://blog.darkdev.se/">','</a>', '<a href="http://github.com">', '</a>') ?></p>
    </div>
</div>