<div class="row">

    <div class="span">
        <h2><?php echo sprintf($this->translate('Placeholder for %s'), 'darkstar') ?></h2>
        <p><?php echo $this->translate('This is an placeholder for the darkstar website and it should bla bla blabl albablablablablabla orkar inte skriva massa skit då ingen annan kommer att se detta i vilket fall, så vad spelar det för roll vad det står för något. Det är en riktigt bra fråga som man inte kommer att få svar på då det inte spelar någon roll vad det står i vilket fall, bla blablaba, detta är så roligt men måste ju tyvärr fylla ut texten en del så att folk förstår vad det ska göra.. eller ... va?! Folk, nej nej, inte folk bara jag då det är jag som utvecklar det så att det blir bara jag som läser detta. Visst är jag rolig som skriver meddelanden till mig själv, sja det är jätte skoj. Nu hoppas jag att texten har blivit lite utfylld så att det går att se ungefär hur det kommer att se ut med mera text här. Tack och hej!') ?></p>
    </div>
</div>