<div class="row">

    <div class="span">
        <h2><?php echo sprintf($this->translate('Player profile for %s'), 'blazed') ?></h2>
        <h4><?php echo $this->translate('Details') ?></h4>
        <p><?php echo sprintf($this->translate('Rank: %s<br />Tribe: %s<br />Alliance: %s<br />Planets: %s<br />Population: %s'), '23', 'tribe2', 'darkstar', '3', '4321') ?></p>
<h4><?php echo $this->translate('Description') ?></h4>
        <p>Här kommer det vara massor med text kanske, vad vet jag. Det får ju personen själv välja. </p>

        <h4><?php echo $this->translate('Plantes') ?></h4>
        <table cellpadding="1" cellspacing="1" id="villages">
	<thead>
		<tr>
			<th class="name">Name</th>
			<th>Inhabitants</th>
			<th>Coordinates</th>
		</tr>
	</thead>
	<tbody>
					<tr>
				<td class="name">
											<a href="karte.php?d=469799">as</a>
									</td>
				<td class="inhabitants">
					10				</td>
				<td class="coords">
					<a class="" href="karte.php?x=12&amp;y=-186"><span class="coordinates coordinatesAligned"><span class="coordinatesWrapper"><span class="coordinateX">(12</span><span class="coordinatePipe">|</span><span class="coordinateY">-186)</span></span></span><span class="clear">‎</span></a>				</td>
			</tr>
			</tbody>
</table>
    </div>
</div>